routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Use Illuminate\Support\Facades\Input;
Use App\Edital;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Rota básica para definir as funções do CRUD
Route::resource('biodata', 'BiodataController');

//Rota para para definir as funções do CRUD
Route::resource('startup', 'StartupController');

//Rota para a página de recuperar senha
Route::get('/Recuperar', function(){
    return view('recuperar.trocarSenha');
});

//Rotas para alterar as configurações dos mentores e membros
Route::resource('dadosMentoresMembros', 'DadosMentoresMembrosController');

//Rota para a página de alterar senha
Route::get('/Alterar', function(){
    return view('alterarSenha.alterar');
});

//Rotas para a página de editais
Route::get('/ShowEdital', 'EditalController@index')->name('show');
Route::get('/DetailEdital/{id}', 'EditalController@detailEdital');
Route::post('/ShowEdital', function(){
    $q = Input::get('search');
    if($q != ' '){
        $edital = Edital::where('titulo', 'LIKE' ,'%'.$q.'%')->get();
        if(count($edital) >= 1 ){
            return view('edital.index', compact('edital'));
        }
    }
    return view('edital.index');
});
Route::post('/Create', 'EditalController@inserir')->name('createEdital');
Route::post('/Update/{id}', 'EditalController@update')->name('updateEdital');
Route::get('/RemoveEdital/{id}', 'EditalController@remove');

//Rota para teste de envio de email
Route::get('/Email', 'EmailController@home');
Route::post('/SendEmail', 'EmailController@enviarEmail')->name('enviarEmail');

//Rotas para a página agenda
Route::get('/Agenda', 'AgendaController@index');
Route::post('/AdicionarEvento', function(){
    return "srgfsdf";
});
// Route::get('/AdicionarEvento/{id}', 'AgendaController@editar');
// Route::get('/AdicionarEvento/{id}', 'AgendaController@remover');

app/DadosMentoresMembros.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DadosMentoresMembros extends Model
{
    protected $fillable = [
        'id',
        'nome',
        'dataNasc',
        'especializacao',
        'telefone',
        'endereco',
        'redesSociais',
        'sobre'];

    public function getId(){return $this->id;}
    public function getNome(){return $this->nome;}
    public function getDataNasc(){return $this->dataNasc;}
    public function getEspecializacao(){return $this->especializacao;}
    public function getTelefone(){return $this->telefone;}
    public function getEndereco(){return $this->endereco;}
    public function getRedesSociais(){return $this->redesSociais;}
    public function getSobre(){return $this->sobre;}

}

app/Http/Controllers/DadosMentoresMembrosController.php
<?php

namespace App\Http\Controllers;

use App\DadosMentoresMembros;
use Illuminate\Http\Request;

class DadosMentoresMembrosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dados = DadosMentoresMembros::latest()->paginate(5);
        return view('dadosMentoresMembros.index', compact('dados'))
                ->with('i', (request()->input('page', 1) -1)*5);  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nome' => 'required',
            'dataNasc' => 'required',
            'especializacao' => 'required',
            'telefone' => 'required',
            'endereco' => 'required',
            'redesSociais' => 'required',
            'sobre' => 'required'
        ]);
        DadosMentoresMembros::create($request->all());
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\DadosMentoresMembros  $dadosMentoresMembros
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dados = DadosMentoresMembros::find($id);
        return view('dadosMentoresMembros.edit', compact('dados'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\DadosMentoresMembros  $dadosMentoresMembros
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nome' => 'required',
            'dataNasc' => 'required',
            'especializacao' => 'required',
            'telefone' => 'required',
            'endereco' => 'required',
            'redesSociais' => 'required',
            'sobre' => 'required'
        ]);
        $dados = DadosMentoresMembros::find($id);
        $dados->nome = $request->get('nome');
        $dados->dataNasc = $request->get('dataNasc');
        $dados->especializacao = $request->get('especializacao');
        $dados->telefone = $request->get('telefone');
        $dados->endereco = $request->get('endereco');
        $dados->redesSociais = $request->get('redesSociais');
        $dados->sobre = $request->get('sobre');
        $dados->save();
        return redirect()->route('dadosMentoresMembros.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\DadosMentoresMembros  $dadosMentoresMembros
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, DadosMentoresMembros $dadosMentoresMembros)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\DadosMentoresMembros  $dadosMentoresMembros
     * @return \Illuminate\Http\Response
     */
    public function destroy(DadosMentoresMembros $dadosMentoresMembros)
    {
        //
    }
}

resources/views/dadosMentoresMembros/edit.blade.php
<!-- index.blade.php - Formulário de dados pessoais dos mentores e membros -->
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/3795336791.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.all.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <style>
        .men{
            margin: 10px 0 10px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class='col-md-5 mx-auto'>
            <form action="{{route('dadosMentoresMembros.update', $dados->id)}}" method="post">
                @csrf
                @method('PUT')
                <div class="custom-file row men">
                    <input type="file" class="custom-file-input" name='foto' id="customFile" disabled>
                    <label class="custom-file-label" for="customFile">Sua foto</label>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='nome'  placeholder="* Seu nome" value='{{$dados->nome}}' required>
                </div>
                <div class="form-group row men">
                    <input type="date" class="form-control" name='dataNasc' value='{{$dados->dataNasc}}' required>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='especializacao'  placeholder="Alguma especialização" value='{{$dados->especializacao}}'>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='telefone'  placeholder="Seu telefone" value='{{$dados->telefone}}'>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='endereco'  placeholder="endereco" value='{{$dados->endereco}}'>
                </div>
                <div class="form-group row men">
                    <label for="inputState">Rede social</label>
                    <select id="inputState" class="form-control" name='redesSociais' value='{{$dados->redesSociais}}'>
                        <option selected>Nenhuma</option>
                        <option>Facebook</option>
                        <option>Instagram</option>
                        <option>Gitlab</option>
                    </select>
                </div>
                <div class="form-group row men">
                    <label for="exampleFormControlTextarea1">Sobre você</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" name='sobre' rows="3" value='{{$dados->sobre}}'></textarea>
                </div>
                <button type="submit" class="btn btn-primary mb-2">Salvar</button>
            </form>
        </div>
    </div>
</body>
</html>

resources/views/dadosMentoresMembros/index.blade.php
<!-- index.blade.php - Formulário de dados pessoais dos mentores e membros -->
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/3795336791.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.all.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <style>
        .men{
            margin: 10px 0 10px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class='col-md-5 mx-auto'>
            <form action="{{route('dadosMentoresMembros.store')}}" method="post">
                @csrf
                <div class="custom-file row men">
                    <input type="file" class="custom-file-input" name='foto' id="customFile" disabled>
                    <label class="custom-file-label" for="customFile">Sua foto</label>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='nome'  placeholder="* Seu nome" required>
                </div>
                <div class="form-group row men">
                    <input type="date" class="form-control" name='dataNasc' required>
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='especializacao'  placeholder="Alguma especialização">
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='telefone'  placeholder="Seu telefone">
                </div>
                <div class="form-group row men">
                    <input type="text" class="form-control" name='endereco'  placeholder="endereco">
                </div>
                <div class="form-group row men">
                    <label for="inputState">Rede social</label>
                    <select id="inputState" class="form-control" name='redesSociais'>
                        <option selected>Nenhuma</option>
                        <option>Facebook</option>
                        <option>Instagram</option>
                        <option>Gitlab</option>
                    </select>
                </div>
                <div class="form-group row men">
                    <label for="exampleFormControlTextarea1">Sobre você</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" name='sobre' rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary mb-2">Salvar</button>
            </form>
        </div>
        <div class='col-md-9 mx-auto'>
            <table class="table table-hover table-sm table-dark">
                <tr>
                    <th width = "50px"><b>Id</b></th>   
                    <th width = "180px">Nome</th>
                    <th width='180px'>Data nasc.</th>
                    <th width='180px'>Especialização</th>
                    <th width='180px'>Telefone</th>
                    <th width='180px'>Endereço</th>
                    <th width='180px'>Redes s.</th>
                    <th width = "300px">Action</th>
                </tr>

            @foreach ($dados as $dado)
            <tr>
                <td><b>{{++$i}}.</b></td>
                <td>{{$dado->nome}}</td>
                <td>{{$dado->dataNasc}}</td>
                <td>{{$dado->especializacao}}</td>
                <td>{{$dado->telefone}}</td>
                <td>{{$dado->endereco}}</td>
                <td>{{$dado->redesSociais}}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{route('dadosMentoresMembros.show', $dado->id)}}">Edit</a>
                </td>
            </tr>
            @endforeach
            </table>

        </div>
    </div>
</body>
</html>